### ISSUE TITLE
Make musical staff look like other staves

### ISSUE THREAD

**Issue by mildmojo** [nikolaiwarner/quartetophone#2]
I think typical notation has notes either centered on a staff line or sandwiched between two lines, touching both. Current implementation is a little wonky as screen size changes. Note sizes seem constant.

![Musical staff](https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Piano_staff.png/400px-Piano_staff.png)

**Comment by nikolaiwarner** [comment]
This would be great but I wont have time to add this feature.
